In [1]:
# importando as bibliotecas necessárias

import pandas as pd

In [2]:
# importando os dados

vendas = pd.read_csv("halloween_vendas.csv", encoding="utf-8", sep=",")

In [3]:
# mostrando as primeiras 3 linhas do dataframe

vendas.head(3)

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
0,844,2025-11-21 18:02:35,Fantasia de vampiro,Fantasia,Loja física,Curitiba,3,132.5,72.08,15,Cancelado,Adulto,G,NaN
1,378,2024-10-29 18:41:26,Fantasia de bruxa,FANTASIA!!!,Loja física,Maringá,3,110.0,57.00,5,Concluído,Adulto,M,2024-11-03 18:41:26
2,953,2025-09-05 21:16:09,Fantasia de bruxa,Fantasia,Web,Maringá,2,116.6,60.42,5,Concluído,Adulto,M,2025-09-10 21:16:09

In [4]:
vendas.shape

(1500, 14)

In [5]:
vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pedido_id       1500 non-null   int64
 1   data_venda      1500 non-null   str
 2   produto         1500 non-null   str
 3   categoria       1482 non-null   str
 4   canal_venda     1500 non-null   str
 5   cidade          1500 non-null   str
 6   quantidade      1500 non-null   int64
 7   preco_unitario  1488 non-null   float64
 8   custo_unitario  1493 non-null   float64
 9   desconto_pct    1500 non-null   int64
 10  status_pedido   1500 non-null   str
 11  publico         1500 non-null   str
 12  tamanho         1500 non-null   str
 13  data_entrega    1357 non-null   str
dtypes: float64(2), int64(3), str(9)
memory usage: 164.2 KB

### Verificando os valores únicos das colunas

In [6]:
# Verificando os valores presentes na coluna produto
# Para identificar nomes diferentes para o mesmo produto

vendas["produto"].value_counts()

produto
Fantasia de vampiro     272
Chapeu de bruxa         272
Fantasia de bruxa       255
Fantasia de abobora     240
Mascara assustadora     237
Fantasia de fantasma    224
Name: count, dtype: int64

In [7]:
# Verificando os valores presentes na coluna categoria 
# Para identificar nomes diferentes para a mesma categoria

# Para esta coluna precisaremos realizar um tratamento nos valores 
# pois as categorias fantasia e acessorio foram escritas de diversas maneiras

vendas["categoria"].value_counts()

categoria
Fantasia            892
Acessorio           459
 Fantasia            48
  FANTASIA!!!        39
 Acessorio           28
  ACESSORIO!!!       16
Name: count, dtype: int64

In [8]:
# Verificando os valores presentes na coluna canal_venda
# Para identificar nomes diferentes para o mesmo canal de venda

# Para esta coluna precisaremos realizar um tratamento nos valores 
# pois os canais de venda estão com nomes divergentes dos canais padrão

vendas["canal_venda"].value_counts()

canal_venda
Web              646
Loja física      535
Mercado          274
 web              20
 loja física      16
 mercado           9
Name: count, dtype: int64

In [9]:
# Verificando os valores presentes na coluna cidade
# Para identificar nomes diferentes para a mesma cidade

vendas["cidade"].value_counts()

cidade
Londrina    396
Cascavel    378
Maringá     375
Curitiba    351
Name: count, dtype: int64

In [10]:
# Verificando os valores presentes na coluna status_pedido
# Para identificar nomes diferentes para o mesmo status de pedido

vendas["status_pedido"].value_counts()

status_pedido
Concluído    1345
Cancelado     109
Devolvido      46
Name: count, dtype: int64

In [11]:
# Verificando os valores presentes na coluna publico
# Para identificar nomes diferentes para o mesmo tipo de público

vendas["publico"].value_counts()

publico
Adulto      527
Todos       509
Infantil    464
Name: count, dtype: int64

In [12]:
# Verificando os valores presentes na coluna tamanho
# Para identificar nomes diferentes para o mesmo tamanho de produto

vendas["tamanho"].value_counts()

tamanho
Unico    509
M        479
G        272
P        240
Name: count, dtype: int64

Precisaremos tratar os valores das colunas "categoria" e "canal_venda"

In [13]:
# Verificar quais colunas possuem valores NaN

vendas.isna().sum()

pedido_id           0
data_venda          0
produto             0
categoria          18
canal_venda         0
cidade              0
quantidade          0
preco_unitario     12
custo_unitario      7
desconto_pct        0
status_pedido       0
publico             0
tamanho             0
data_entrega      143
dtype: int64

Em 4 colunas temos linhas com valores nulos, teremos que analisar o contexto de cada informação ausente e verificar a necessidade de tratamento

In [14]:
data_entrega_nan = vendas.loc[vendas["data_entrega"].isna() == True]

In [15]:
data_entrega_nan.head()

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
0,844,2025-11-21 18:02:35,Fantasia de vampiro,Fantasia,Loja física,Curitiba,3,132.5,72.08,15,Cancelado,Adulto,G,NaN
8,186,2024-08-17 22:17:18,Fantasia de fantasma,Fantasia,Web,Londrina,2,75.0,39.00,0,Cancelado,Infantil,M,NaN
21,662,2024-10-21 19:27:01,Fantasia de vampiro,Fantasia,Web,Londrina,2,125.0,68.00,0,Cancelado,Adulto,G,NaN
49,1170,2025-08-19 22:20:19,Fantasia de abobora,Fantasia,Web,Maringá,2,90.1,46.64,0,Concluído,Infantil,P,NaN
59,896,2025-09-25 21:51:50,Fantasia de fantasma,Fantasia,Web,Maringá,2,79.5,41.34,0,Cancelado,Infantil,M,NaN

In [16]:
data_entrega_nan["status_pedido"].value_counts()

status_pedido
Cancelado    109
Concluído     34
Name: count, dtype: int64

In [17]:
data_entrega_nan.loc[data_entrega_nan["status_pedido"] == "Concluído"]

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
49,1170,2025-08-19 22:20:19,Fantasia de abobora,Fantasia,Web,Maringá,2,90.10,46.64,0,Concluído,Infantil,P,NaN
117,990,2025-10-13 20:00:16,Fantasia de fantasma,Fantasia,web,Londrina,2,79.50,41.34,0,Concluído,Infantil,M,NaN
152,740,data_invalida,Fantasia de abobora,Fantasia,Web,Curitiba,2,85.00,44.00,25,Concluído,Infantil,P,NaN
164,630,2024-11-03 12:14:23,Chapeu de bruxa,Acessorio,Mercado,Londrina,-1,22.00,8.00,10,Concluído,Todos,Unico,NaN
226,45,2024-11-15 12:17:08,Mascara assustadora,Acessorio,Mercado,Maringá,4,35.00,12.00,15,Concluído,Todos,Unico,NaN
240,720,2024-08-05 21:36:11,Fantasia de fantasma,NaN,Web,Cascavel,2,75.00,39.00,0,Concluído,Infantil,M,NaN
255,370,data_invalida,Fantasia de vampiro,Fantasia,Web,Curitiba,1,125.00,68.00,0,Concluído,Adulto,G,NaN
301,270,2024-10-27 09:44:47,Fantasia de abobora,FANTASIA!!!,Mercado,Curitiba,5,85.00,44.00,0,Concluído,Infantil,P,NaN
320,810,2025-10-25 19:29:32,Fantasia de vampiro,FANTASIA!!!,Web,Curitiba,3,132.50,72.08,0,Concluído,Adulto,G,NaN
341,945,2025-10-27 18:18:33,Fantasia de bruxa,FANTASIA!!!,Web,Londrina,3,116.60,60.42,0,Concluído,Adulto,M,NaN
357,675,2024-10-15 11:07:27,Mascara assustadora,ACESSORIO!!!,Loja física,Londrina,3,35.00,12.00,0,Concluído,Todos,Unico,NaN
380,135,2024-10-22 18:44:20,Fantasia de vampiro,FANTASIA!!!,Web,Londrina,1,125.00,68.00,0,Concluído,Adulto,G,NaN
413,315,2024-10-12 18:09:59,Mascara assustadora,Acessorio,Mercado,Maringá,3,35.00,12.00,0,Concluído,Todos,Unico,NaN
447,360,2024-10-27 15:54:17,Chapeu de bruxa,Acessorio,Loja física,Cascavel,2,22.00,8.00,10,Concluído,Todos,Unico,NaN
530,1485,2025-08-31 19:38:12,Fantasia de abobora,FANTASIA!!!,web,Maringá,1,90.10,46.64,0,Concluído,Infantil,P,NaN
581,540,2024-10-02 21:09:13,Fantasia de vampiro,FANTASIA!!!,Web,Maringá,3,125.00,68.00,5,Concluído,Adulto,G,NaN
602,1350,2025-09-23 16:24:37,Fantasia de vampiro,FANTASIA!!!,Loja física,Curitiba,1,132.50,72.08,10,Concluído,Adulto,G,NaN
714,1480,data_invalida,Fantasia de vampiro,Fantasia,Web,Cascavel,2,132.50,72.08,0,Concluído,Adulto,G,NaN
723,1305,2025-10-02 11:24:13,Chapeu de bruxa,Acessorio,Mercado,Curitiba,4,23.32,8.48,0,Concluído,Todos,Unico,NaN
809,450,2024-09-16 19:33:38,Fantasia de bruxa,Fantasia,Web,Cascavel,1,110.00,57.00,5,Concluído,Adulto,M,NaN
840,855,2025-10-03 18:06:38,Chapeu de bruxa,Acessorio,Web,Cascavel,1,23.32,8.48,0,Concluído,Todos,Unico,NaN
862,495,2024-10-15 19:35:05,Fantasia de abobora,Fantasia,web,Cascavel,2,85.00,44.00,5,Concluído,Infantil,P,NaN
884,1110,data_invalida,Fantasia de bruxa,Fantasia,Web,Cascavel,1,116.60,60.42,0,Concluído,Adulto,M,NaN
932,1395,2025-08-03 19:57:36,Fantasia de vampiro,Fantasia,Web,Curitiba,1,132.50,72.08,0,Concluído,Adulto,G,NaN
1107,585,2024-08-17 11:04:38,Fantasia de vampiro,Fantasia,Loja física,Curitiba,3,125.00,68.00,5,Concluído,Adulto,G,NaN
1168,90,2024-09-24 20:14:04,Fantasia de bruxa,Fantasia,Web,Londrina,2,110.00,57.00,5,Concluído,Adulto,M,NaN
1200,900,2025-10-18 19:55:27,Chapeu de bruxa,Acessorio,Mercado,Londrina,4,23.32,8.48,0,Concluído,Todos,Unico,NaN
1210,1035,2025-10-09 18:07:09,Chapeu de bruxa,Acessorio,Loja física,Maringá,1,23.32,8.48,0,Concluído,Todos,Unico,NaN
1251,225,2024-09-16 17:12:35,Fantasia de bruxa,Fantasia,Loja física,Londrina,1,110.00,57.00,0,Concluído,Adulto,M,NaN
1265,180,2024-11-06 16:50:03,Fantasia de abobora,Fantasia,Loja física,Curitiba,1,85.00,44.00,20,Concluído,Infantil,P,NaN
1312,1125,2025-10-23 12:38:12,Fantasia de bruxa,Fantasia,Loja física,Cascavel,1,NaN,60.42,5,Concluído,Adulto,M,NaN
1332,1215,2025-11-21 21:23:17,Fantasia de abobora,FANTASIA!!!,Web,Curitiba,1,90.10,46.64,10,Concluído,Infantil,P,NaN
1421,765,2025-10-03 21:47:16,Fantasia de vampiro,Fantasia,Web,Curitiba,2,132.50,72.08,0,Concluído,Adulto,G,NaN
1448,1260,2025-10-06 11:49:25,Chapeu de bruxa,Acessorio,Loja física,Maringá,-1,23.32,8.48,0,Concluído,Todos,Unico,NaN

Nas informações acima podemos observar que existem 34 registros sem data de entrega, porém com status do pedido concluído. Então fica descartada a hipótese de que a falta de dados na coluna data_entrega é consequência somente de pedidos que não foi realizado a entrega, pois existem registros de produtos que foram entregues porém sem o registro da data.

Uma segunda hipótese para justificar registros com status concluído porém sem data de entrega, seria que os registros estavam duplicados e a data de entrega foi gravada em apenas uma das linhas duplicadas

In [18]:
# Verificando se há linhas duplicadas no dataset original 
# 

print(f"Quantidade de linhas duplicadas no dataset: {vendas.duplicated().sum()}")

Quantidade de linhas duplicadas no dataset: 0

In [19]:
# Verificando se há mais de uma linha com o mesmo pedido_id

print(f"Número de registros com o id repetido: {vendas.duplicated(subset=["pedido_id"]).sum()}")

Número de registros com o id repetido: 0

In [20]:
print(f"Número de registros com id único: {vendas["pedido_id"].nunique()}")

Número de registros com id único: 1500

Após a análise das informações acima podemos descartar a segunda hipótese também, pois nos dados não há registros com pedido_id duplicados

INICIO TRATAMENTO DO DATASET

In [21]:
vendas_tratado = vendas.copy()

In [22]:
vendas_tratado.shape

(1500, 14)

Tratamento de strings

In [23]:
# Criação da função normalizar_string
# .strip - remove os espaços
# .lower - deixa as letras em minúsculo
# replace r"[^\w\s]" - mantém apenas os caracteres alfanuméricos e espaços

def normalizar_string(texto : str) -> str:
    """ 
    Função para remover espaços desnecessários, deixar todas as letras minúsculas e remover pontuações de uma string 
    """
    
    texto = texto.str.strip().str.lower().str.replace(r"[^\w\s]", "", regex=True)
    return texto

In [24]:
# Aplicando a função normalizar_string para formatar os valores da coluna categoria

vendas_tratado["categoria"] = normalizar_string(vendas_tratado["categoria"])

In [25]:
vendas_tratado["categoria"].value_counts()

categoria
fantasia     979
acessorio    503
Name: count, dtype: int64

In [26]:
# Formatando os valores da coluna canal_venda
# .strip() remove os espaços
# .capitalize() deixa a primeira letra maiúscula

vendas_tratado["canal_venda"] = vendas_tratado["canal_venda"].str.strip().str.capitalize()

In [27]:
vendas_tratado["canal_venda"].value_counts()

canal_venda
Web            666
Loja física    551
Mercado        283
Name: count, dtype: int64

Tratamento de datas

In [ ]:
# Primeiro renomeamos a coluna original para manter a identificação

vendas_tratado = vendas_tratado.rename(columns={"data_venda" : "data_venda_original"})

In [ ]:
# Criaremos uma nova coluna para armazenar as datas no formato datetime

vendas_tratado["data_venda_tratado"] = pd.to_datetime(vendas_tratado["data_venda_original"], format="%Y-%m-%d %H:%M:%S", errors="coerce")

In [ ]:
# Verificamos se a nova coluna criada ficou no formato correto

vendas_tratado.dtypes

pedido_id                       int64
data_venda_original               str
produto                           str
categoria                         str
canal_venda                       str
cidade                            str
quantidade                      int64
preco_unitario                float64
custo_unitario                float64
desconto_pct                    int64
status_pedido                     str
publico                           str
tamanho                           str
data_entrega                      str
data_venda_tratado     datetime64[us]
dtype: object

In [ ]:
# Agora conforme pedido criaremos uma coluna para representação da data no formato brasileiro

vendas_tratado["data_venda"] = vendas_tratado["data_venda_tratado"].dt.strftime("%d/%m/%Y")

Tratamento de valores nulos

In [28]:
vendas_tratado["categoria"] = vendas_tratado["categoria"].fillna("sem categoria")

In [51]:
vendas_tratado.isna().sum()

pedido_id                0
data_venda_original      0
produto                  0
categoria                0
canal_venda              0
cidade                   0
quantidade               0
preco_unitario          12
custo_unitario           7
desconto_pct             0
status_pedido            0
publico                  0
tamanho                  0
data_entrega           143
data_venda_tratado       4
data_venda               4
dtype: int64